name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: mushtaq4web
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push snake to output branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist

